services:
  db:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle_test_db
    ports:
      - "1521:1521"  # Default Oracle DB port
    environment:
      ORACLE_PASSWORD: test_pass
      ORACLE_DATABASE: test_db
      APP_USER: test_user
      APP_USER_PASSWORD: test_pass
    volumes:
      - oracle_data:/opt/oracle/oradata     # persistent data volume
      - ./init:/container-entrypoint-initdb.d # init scripts (nonstandard, see below)
    restart: unless-stopped

volumes:
  oracle_data:
