-- Copyright (c) Saga Inc.
-- Distributed under the terms of the GNU Affero General Public License v3.0 License.

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) UNIQUE NOT NULL
);

INSERT ALL
  INTO users (name, email) VALUES ('Alice', 'alice@example.com')
  INTO users (name, email) VALUES ('Bob', 'bob@example.com')
  INTO users (name, email) VALUES ('Charlie', 'charlie@example.com')
SELECT * FROM dual;
