# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: aaron@sagacollab.com
author_name: Saga Inc.
has_binder: false
has_settings: false
kind: frontend
labextension_name: mito-sql-cell
project_short_description: JupyterLab extension adding support for SQL cells.
python_name: mito_sql_cell
repository: https://github.com/mito-ds/mito
test: true

