# Copyright (c) Saga Inc.
# Distributed under the terms of the GNU Affero General Public License v3.0 License.

[build-system]
requires = ["jupyterlab~=4.0", "setuptools>=68.0.0", "wheel"]
build-backend = "setuptools.build_meta"
