name: Test - Mito AI Jest Frontend

on:
  push:
    branches: [ dev ]
    paths:
      - 'mito-ai/src/**'
      - 'mito-ai/package.json'
      - 'mito-ai/jest.config.js'
      - 'mito-ai/src/tests/**'
  pull_request:
    paths:
      - 'mito-ai/src/**'
      - 'mito-ai/package.json'
      - 'mito-ai/jest.config.js'
      - 'mito-ai/src/tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-mitoai-frontend:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: mito-ai/package-lock.json

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyterlab

    - name: Install dependencies
      run: |
        cd mito-ai
        jlpm install

    - name: Build project
      run: |
        cd mito-ai
        jlpm run build:lib && jupyter labextension build --development True .

    - name: Run Jest tests
      run: |
        cd mito-ai
        jlpm test

    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mitoai-frontend-coverage-${{ github.run_id }}
        path: mito-ai/coverage/
        retention-days: 14 