name: Test - mito-ai mypy

on:
  push:
    branches: [ dev ]
    paths:
      - 'mito-ai/**'
  pull_request:
    paths:
      - 'mito-ai/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-mito-ai-mypy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: mito-ai/setup.py
    - name: Install dependencies
      run: |
        cd mito-ai
        pip install -e ".[test]"
    - name: Check types with MyPY
      run: |
        mypy mito-ai/mito_ai/ --ignore-missing-imports